### ISSUE TITLE
Include warzone map

### ISSUE THREAD

**Issue by ecumene** [TDrake38/warzone-drop#2]
https://www.google.com/search?q=warzone+map&client=ubuntu&hs=akc&channel=fs&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi5vtePr6fyAhVbMVkFHea8D_MQ_AUoAXoECAEQAw&biw=1920&bih=890#imgrc=WKIAut_31ZJTfM

**Comment by TDrake38** [comment]
Complete.
