### ISSUE TITLE
Record postitions on map in an array

### ISSUE THREAD

**Issue by ecumene** [TDrake38/warzone-drop#3]
```
const locations = [
    {
        name: "Supermarket",
        top: 100,
        left: 100,
    },
    ...
}
```

```
locations.forEach(...)
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by TDrake38** [comment]
Added  the locations. Created a button that randomly picks one of the locations and displays the name.
